# robotpkg Makefile for:	image/ros-openni2-camera
# Created:			 Séverin Lemaignan on Tue, 17 Jun 2014
#

ROS_PKG=		openni2_camera
ROS_VERSION=		0.1.0
ROS_REPO=		ros-drivers

CATEGORIES=		image
ROS_COMMENT=		ROS driver for OpenNI2 depth (+ RGB) cameras. 

include ../../meta-pkgs/ros-base/Makefile.common

include ../../devel/ros-catkin/depend.mk
include ../../devel/ros-nodelet-core/depend.mk
include ../../devel/ros-ros/depend.mk
include ../../image/ros-image-common/depend.mk
include ../../interfaces/ros-common-msgs/depend.mk
include ../../middleware/ros-comm/depend.mk
include ../../middleware/ros-dynamic-reconfigure/depend.mk
include ../../mk/sysdep/openni2.mk
include ../../mk/robotpkg.mk
